### ISSUE TITLE
paypalclient is_primittive check

### ISSUE THREAD

**Issue by daniel-butler** [ThorstenMauch/oscar-paypalcheckout#3]
It looks like the check for `is_primittive` checks for a str twice. Is it supposed to be something else?

```
    def is_primittive(self, data):
        return isinstance(data, str) or isinstance(data, str) or isinstance(data, int)
```

**Comment by ThorstenMauch** [comment]
I see you solve this. I was redundant because for python v2 it needed  isinstance(data, unicode),
